# Development configuration overrides
# This file overrides settings in _config.yml for local development

baseurl: "" # Empty for local development
url: "http://localhost:4000" # Local development URL

# Enable more verbose output for debugging
incremental: false
safe: false