# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sour Theme
email: jeremy.cardona@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A template for a responsive and SEO-friendly Jekyll theme built with TailwindCSS and DaisyUI components. 
baseurl: "/jekyll-theme-sour" # the subpath of your site, e.g. /blog
url: "https://jeremycardona.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: cyberdevblog
github_username: jeremycardona
author: Sour Theme

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-toc
  - jekyll-reading-time
  - jekyll-gist
  # - jekyll-katex  # Disabled due to JS runtime issues
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll-last-modified-at
  - jekyll-youtube
  - rouge

# Plugin configurations
# Remove old jekyll-paginate settings - using jekyll-paginate-v2
# paginate: 10
# paginate_path: "/blog/page:num/"

# jekyll-paginate-v2 configuration
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Table of contents
toc:
  min_level: 2
  max_level: 4

# Comments configuration (Utterances)
comments:
  enabled: true
  provider: "utterances"
  utterances:
    repo: "jeremycardona/jekyll-theme-sour"  # Your GitHub username/repository
    issue-term: "pathname"                    # Use page pathname as issue title
    theme: "preferred-color-scheme"           # Matches your site's theme switching
    crossorigin: "anonymous"

# Include _pages directory for custom pages
include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package*.json
  - tailwind.config.js
  - src/
  - Makefile
  - README.md
  - _config_dev.yml